global using Application.Common.CQRS;
global using Application.Common.Events;
global using Application.Common.Exceptions;
global using Application.Common.Interfaces;
global using Application.Common.Persistence;
global using Domain.Events;
global using FluentValidation;
global using Mapster;
global using MediatR;
